name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    name: Build and Test the code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependences    
      run: go mod download && go mod verify

    - name: Build
      run: go build cmd/main/main.go
    
    - name: Test
      run: go test -v ./...  

  push:
    needs: test
    name: Pushing to the docker registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4


    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: "monootaku"
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: monootaku/chat

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
