name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
      
    - name: Build
      run: go build cmd/main/main.go
    
    - name: Test
      run: go test -v ./...  

#   push:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4

#     - name: Set up Go
#       uses: actions/setup-go@v4
#       with:
#         go-version: '1.21'

#     - name: Build
#       run: go build -v ./...

#     - name: Test
#       run: go test -v ./...
